version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    assignees:
      - "ryanmab"

  - package-ecosystem: npm
    directory: /examples/typescript-jest/
    schedule:
      interval: daily
    assignees:
      - "ryanmab"
